#!/bin/sh

# Copyright (C) 2010-2012 Javier Palacios
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License Version 2
# as published by the Free Software Foundation.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.

# ameba-updater          Start/Stop the amebaC3 client daemon.
#
# chkconfig: - 90 60
# description: aupd is the agent program of amebaC3, in charge of perform \
#              the system status verifications and upgrades
# processname: aupd
# config: /etc/aupd.conf

PROGRAM=/usr/bin/aupd

[ ! -x ${PROGRAM} ] && exit

start() {
    pid=`pgrep -f -P 1 ${PROGRAM}`
    if [ -n "${pid}" ] ; then
        echo "Already started"
    else
        echo "Starting"
        ${PROGRAM} pulldaemon
    fi
}

stop() {
    pid=`pgrep -f -P 1 ${PROGRAM}`
    if [ -n "${pid}" ] ; then
        echo "Stopping"
        kill -TERM ${pid}
    else
        echo "Already stopped"
    fi
}

running() {
    pid=`pgrep -f -P 1 ${PROGRAM}`
    if [ -n "${pid}" ] ; then
        return 0
    fi
    return 1
}

status() {
    running
    if [ $? -eq 0 ] ; then
        echo "Running"
        exit 0
    else
        echo "Stopped"
        exit 1
    fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  condrestart)
    running
    if [ $? -eq 0 ] ; then
        stop
        start
    fi
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 start|stop|restart|condrestart|status"
    exit 1
esac

exit $?

